### ISSUE TITLE
Deprecated commands in actions set-output

### ISSUE THREAD

**Issue by ff6347** [technologiestiftung/erfrischungskarte-frontend#132]
The GitHub actions commands set-output and set-state will be deprecated see this blog post --> https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This repo is using the set-output

A fix for setting the node version could be the following action step:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Set nvmrc version as .env variable
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
            - name: Use Node.js (.nvmrc)
              uses: actions/setup-node@v3
              with:
                node-version: "${{ env.NODE_VERSION }}"
```
